root:         ./root
gitbook:      ">= 3.0.0"
title:        "Chatie Documentations"
description:  "Tutorials, API, and Support."
author:       "Rui LI <ruiruibupt@gmail.com>"
links: 
  - 
    sidebar: 
      - 
        Home: "https://www.chatie.io"
